# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# KEYLOGGER
# =============================================================================

  keylogger:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./code
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - keylogger

# =============================================================================
# NETWORK
# =============================================================================

networks:
  keylogger:
